ERROR 2024-08-17 12:22:17,777 log 1256112 139829652952960 Internal Server Error: /api/board/read
Traceback (most recent call last):
  File "/home/apps/my_wiki/./api/views.py", line 45, in read
    serializer = BoardSerializer(boards, many=True)
NameError: name 'BoardSerializer' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/apps/my_wiki/./api/views.py", line 48, in read
    return Response({'error': e.message}, status=500)
AttributeError: 'NameError' object has no attribute 'message'
WARNING 2024-08-17 12:34:12,519 log 1263891 140530329446272 Method Not Allowed: /api/board/write
WARNING 2024-08-17 14:12:46,630 log 1279908 140006620948352 Not Found: /ab2g
WARNING 2024-08-17 14:12:47,784 log 1279908 140006620948352 Not Found: /ab2h
WARNING 2024-08-17 14:12:48,747 log 1279908 140006620948352 Not Found: /alive.php
WARNING 2024-08-17 14:12:57,495 log 1279908 140006620948352 Not Found: /t4
WARNING 2024-08-17 14:12:59,261 log 1279908 140006620948352 Not Found: /favicon.ico
WARNING 2024-08-17 14:13:01,486 log 1279908 140006620948352 Not Found: /teorema505
WARNING 2024-08-17 15:44:05,727 log 1279908 140006620948352 Not Found: /actuator/gateway/routes
WARNING 2024-08-17 17:51:16,471 log 1279908 140006620948352 Not Found: /aaa9
WARNING 2024-08-17 17:51:18,728 log 1279908 140006620948352 Not Found: /aab9
WARNING 2024-08-17 17:51:36,635 log 1279908 140006620948352 Not Found: /aaa9
WARNING 2024-08-17 17:51:38,154 log 1279908 140006620948352 Not Found: /aab9
WARNING 2024-08-17 18:41:58,461 log 1279908 140006620948352 Not Found: /favicon.ico
WARNING 2024-08-17 18:43:57,608 log 1279908 140006620948352 Not Found: /favicon.ico
WARNING 2024-08-17 19:44:33,852 log 1279908 140006620948352 Not Found: /.env
WARNING 2024-08-17 19:44:34,573 log 1279908 140006620948352 Forbidden (Referer checking failed - no Referer.): /
WARNING 2024-08-17 20:35:19,353 log 1279908 140006620948352 Not Found: /favicon.ico
WARNING 2024-08-17 21:25:55,788 log 1279909 140006620948352 Not Found: /.env
WARNING 2024-08-17 22:07:58,515 log 1279908 140006620948352 Not Found: /hello.world
WARNING 2024-08-17 22:07:59,284 log 1279908 140006620948352 Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:00,538 log 1279908 140006620948352 Not Found: /vendor/phpunit/phpunit/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:02,280 log 1279908 140006620948352 Not Found: /vendor/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:03,537 log 1279908 140006620948352 Not Found: /vendor/phpunit/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:04,984 log 1279908 140006620948352 Not Found: /vendor/phpunit/phpunit/LICENSE/eval-stdin.php
WARNING 2024-08-17 22:08:05,722 log 1279908 140006620948352 Not Found: /vendor/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:06,229 log 1279908 140006620948352 Not Found: /phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:06,521 log 1279908 140006620948352 Not Found: /phpunit/phpunit/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:06,757 log 1279908 140006620948352 Not Found: /phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:06,951 log 1279908 140006620948352 Not Found: /phpunit/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:07,481 log 1279908 140006620948352 Not Found: /lib/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:07,654 log 1279908 140006620948352 Not Found: /lib/phpunit/phpunit/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:07,764 log 1279908 140006620948352 Not Found: /lib/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:07,879 log 1279908 140006620948352 Not Found: /lib/phpunit/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:07,993 log 1279908 140006620948352 Not Found: /lib/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:08,785 log 1279908 140006620948352 Not Found: /laravel/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:09,276 log 1279908 140006620948352 Not Found: /www/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:09,438 log 1279908 140006620948352 Not Found: /ws/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:10,251 log 1279908 140006620948352 Not Found: /yii/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:10,446 log 1279908 140006620948352 Not Found: /zend/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:11,289 log 1279908 140006620948352 Not Found: /ws/ec/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:11,643 log 1279908 140006620948352 Not Found: /V2/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:12,025 log 1279908 140006620948352 Not Found: /tests/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:12,389 log 1279908 140006620948352 Not Found: /test/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:12,838 log 1279908 140006620948352 Not Found: /testing/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:13,378 log 1279908 140006620948352 Not Found: /api/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:14,521 log 1279908 140006620948352 Not Found: /demo/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:15,286 log 1279908 140006620948352 Not Found: /cms/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:16,633 log 1279908 140006620948352 Not Found: /crm/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:18,809 log 1279908 140006620948352 Not Found: /backup/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:19,361 log 1279908 140006620948352 Not Found: /blog/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:20,008 log 1279908 140006620948352 Not Found: /workspace/drupal/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:21,049 log 1279908 140006620948352 Not Found: /panel/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:21,519 log 1279908 140006620948352 Not Found: /public/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:22,329 log 1279908 140006620948352 Not Found: /apps/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:22,694 log 1279908 140006620948352 Not Found: /app/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
WARNING 2024-08-17 22:08:22,972 log 1279908 140006620948352 Not Found: /index.php
WARNING 2024-08-17 22:08:23,215 log 1279908 140006620948352 Not Found: /public/index.php
WARNING 2024-08-17 22:08:23,803 log 1279908 140006620948352 Not Found: /index.php
WARNING 2024-08-17 22:08:24,054 log 1279908 140006620948352 Not Found: /index.php
WARNING 2024-08-17 22:17:18,707 log 1279908 140006620948352 Not Found: /_profiler/phpinfo
WARNING 2024-08-17 22:18:00,722 log 1279908 140006620948352 Not Found: /_profiler/phpinfo
WARNING 2024-08-18 01:47:45,006 log 1279908 140006620948352 Not Found: /v1.44/exec/bfd6860678098073744e59ee64a39c573ccefabfcad759a140c7ca8ecf1a3224/json
WARNING 2024-08-18 01:55:28,745 log 1314091 140307329402752 Not Found: /favicon.ico
WARNING 2024-08-18 03:37:16,102 log 1340718 140304466384768 Not Found: /a
WARNING 2024-08-18 03:37:21,098 log 1340718 140304466384768 Not Found: /a
WARNING 2024-08-18 03:39:14,536 log 1341510 140280323905408 Not Found: /about
WARNING 2024-08-18 03:39:29,310 log 1341510 140280323905408 Not Found: /about
WARNING 2024-08-18 03:44:40,795 log 1341511 140280323905408 Not Found: /about
WARNING 2024-08-18 04:05:49,551 log 1345198 140619122845568 Not Found: /about
WARNING 2024-08-18 04:06:34,702 log 1345198 140619122845568 Not Found: /.env
WARNING 2024-08-18 04:19:28,126 log 1347572 139684273842048 Not Found: /about
WARNING 2024-08-18 04:19:30,414 log 1347572 139684273842048 Not Found: /about
WARNING 2024-08-18 04:20:24,556 log 1347572 139684273842048 Not Found: /about
WARNING 2024-08-18 04:20:27,172 log 1347572 139684273842048 Not Found: /ppt
ERROR 2024-08-18 04:31:15,664 log 1348884 140623005439872 Internal Server Error: /about
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2024-08-18 04:31:17,154 log 1348888 140623005439872 Internal Server Error: /about
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2024-08-18 04:31:17,995 log 1348884 140623005439872 Internal Server Error: /about
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2024-08-18 04:31:23,950 log 1348888 140623005439872 Internal Server Error: /
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2024-08-18 04:31:24,185 log 1348888 140623005439872 Internal Server Error: /
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2024-08-18 04:31:25,701 log 1348888 140623005439872 Internal Server Error: /
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/root/.cache/pypoetry/virtualenvs/my-wiki-n6iennJt-py3.10/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
